{
 "title": "MQTT - PDM1106J Metrics",
 "tags": [
  "mqtt",
  "pdm1106j"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Voltage (V)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pdm_metric_value{topic=\"PDM1106J/voltage\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Power (W)",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pdm_metric_value{topic=\"PDM1106J/power\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Current (A)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ampere" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pdm_metric_value{topic=\"PDM1106J/current\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Energy (kWh)",
   "type": "stat",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pdm_metric_value{topic=\"PDM1106J/energy\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Power Factor",
   "type": "stat",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pdm_metric_value{topic=\"PDM1106J/pf\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Frequency (Hz)",
   "type": "stat",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pdm_metric_value{topic=\"PDM1106J/fr\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}